//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int Id { get; set; }
        public string NombreProyecto { get; set; }
        public string NombreCliente { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Colaborador { get; set; }
        public bool Estado { get; set; }

    
        public virtual Usuario Usuario { get; set; }
    }
}
